version: '3.8'

volumes:
  influxdb_data:
  mosquitto_data:
  grafana_data:

networks:
  simac_net:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 1883"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks: [simac_net]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    networks: [simac_net]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    environment:
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    volumes:
      - ./mosquitto/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    # Se já tiver um telegraf.conf pronto, mapeie em read-only:
    # volumes:
    #   - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    # Caso não mapeie, faça o config via variáveis ou copie depois com docker cp.
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    networks: [simac_net]

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_DEFAULT_THEME=dark
      - GF_INSTALL_PLUGINS=grafana-influxdb-flux-datasource
      # Evite tentar instalar plugin no boot em servidor sem internet:
      # - GF_INSTALL_PLUGINS=grafana-influxdb-flux-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped
    networks: [simac_net]
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
